version: '3'

services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!
      MONGO_INITDB_DATABASE: tcc-db-api
    volumes:
      - ./mongodb/init_mongo_user.sh:/docker-entrypoint-initdb.d/init_mongo_user.sh
      - ./mongodb/init_mongo_data.js:/docker-entrypoint-initdb.d/init_mongo_data.js:ro
      - mongo-volume:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo-volume: